batch_size: 128
epochs: 50
lr_start: 0.002
lr_end: 0.001
weight_decay: 0.00001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: outputs\2024-07-17\00-44-15\model_last.pt