batch_size: 128
epochs: 80
lr_start: 0.003
lr_end: 0.0005
weight_decay: 0.000005

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: outputs\2024-07-17\00-44-15\model_last.pt